###############################
# SYSTEMS
###############################
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: developer-hub-ai-assistant
  description: "Generative AI for Red Hat Developer Hub and Backstage."
  tags:
    - genai
  links:
    - url: https://backstage.io/docs/overview/what-is-backstage/ 
      title: What is Backstage? 
      type: website 
      icon: WebAsset
spec: 
  owner: user:bwilcock
  profile:
    displayName: Red Hat Developer Hub AI Assistant
---
####################################
# COMPONENTS
####################################
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vLLM
  description: 'AI Model server popular for hosting large language models in enterprise settings. OpenAI API compatible. '
  links:
    - url: https://docs.vllm.ai/en/stable/
      title: vLLM Documentation
      type: website
      icon: WebAsset
  tags:
    - genai
spec:
  type: ai-model-server
  owner: user:bwilcock
  system: developer-hub-ai-assistant
  lifecycle: production
  providesApis:
    - openai-api
  dependsOn: 
    - resource:granite-8b-code-instruct
    - api:openai-api
  profile:
    displayName: "vLLM AI Model Server"
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-hub-ai-assistant-plugin
  description: 'Red Hat developer Hub AI Assistant Plugin for Backstage. Provides a convenient chat interface and works with multiple AI backends including ChatGPT, Ollama, vLLM, etc.'
  # links:
  #   - url: https://docs.vllm.ai/en/stable/
  #     title: Code (Open Source)
  #     type: website
  #     icon: WebAsset
  tags:
    - genai
    - devhub
    - plugins
spec:
  type: backstage-plugin
  owner: user:bwilcock
  system: developer-hub-ai-assistant
  lifecycle: production
  dependsOn: 
    - component:vLLM
    - api:openai-api
  profile:
    displayName: "Red Hat developer Hub AI Assistant Plugin for Backstage"
---
####################################
# RESOURCES
####################################
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: granite-8b-code-instruct
  description: 'IBM Granite is a decoder-only code model for code generative tasks (e.g. fixing bugs, explaining code, documenting code, etc.). Trained with code written in 116 programming languages.'
  links:
    - url: https://github.com/ibm-granite/granite-code-models
      title: IBM Granite Code Repository
      type: website
      icon: WebAsset
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/bwilcock/backstage-catalogs/tree/main/ai-assets-techdocs/models
  tags:
    - genai
    - ibm
    - llm
spec:
  type: ai-model
  owner: user:bwilcock
  system: developer-hub-ai-assistant
  lifecycle: production
  providesApis:
    - openai-api
  dependencyOf: 
    - component:vLLM
  profile:
    displayName: "IBM Granite 8B Code Instruct Model"
######################################
# APIs
######################################
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openai-api
  title: OpenAI API
  description: 'The REST API exposed by ChatGPT and compatible systems such as vLLM, Ollama, etc.'
  tags:
    - api
    - openai
  links:
    - url: https://platform.openai.com/docs/api-reference
      title: OpenAI API Documentation
      type: website
      icon: WebAsset
spec:
  type: api
  owner: user:bwilcock
  system: developer-hub-ai-assistant
  lifecycle: production
  dependencyOf: 
    - component:vLLM
  definition:
    $text: https://github.com/openai/openai-openapi/blob/master/openapi.yaml
