---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tanzu
  description: The Tanzu Organization
  links:
    - url: http://tanzu.vmware.com/
      title: Website
    - url: https://source.vmware.com/
      title: Intranet
spec: 
  type: organization
  profile:
    displayName: Tanzu
    email: tanzu@vmware.com
    picture: https://pbs.twimg.com/profile_images/1233138813939146752/YPCsKoIa_400x400.png
  children: [tanzu-marketing]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tanzu-marketing
  description: The Tanzu Marketing department
spec:
  type: department
  profile:
    displayName: Tanzu Marketing
    email: tanzu-marketing@vmware.com
    picture: https://pbs.twimg.com/profile_images/1233138813939146752/YPCsKoIa_400x400.png
  children: [tanzu-tech-marketing]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tanzu-tech-marketing
  description: The Tanzu Technical Marketing Developer Application Platforms sub-team
spec:
  type: team
  description: This team helps describe the features and benefits of VMware Tanzu platforms (TAP, TAS, etc) to audiences everywhere
  profile:
    displayName: DAP Technical Marketing Team
    picture: https://pbs.twimg.com/profile_images/1233138813939146752/YPCsKoIa_400x400.png
  children: []
  parent: tanzu-marketing
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ben.wilcock
  description: Ben specialises in articulating the virtues of the Tanzu Application Platform to developer audiences.
spec:
  profile:
    displayName: Ben Wilcock
    email: ben@blah.cloud
    picture: https://pbs.twimg.com/profile_images/1577303225677615107/f0lW_xGN_400x400.jpg
  memberOf: [tanzu-tech-marketing]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: myles.gray
  description: Myles specialises in articulating the virtues of the Tanzu Application Platform to operator audiences.
spec:
  profile:
    displayName: Myles Gray
    email: myles@blah.cloud
    picture: https://pbs.twimg.com/profile_images/1143994652296712198/fvfDS9k3_400x400.jpg
  memberOf: [tanzu-tech-marketing]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: keith.lee
  description: Keith is an allround platform expert and accredited VMware vExpert
spec:
  profile:
    displayName: Keith Lee
    email: keith@blah.cloud
    picture: https://pbs.twimg.com/profile_images/1567175334063230976/BpcUztUb_400x400.jpg
  memberOf: [tanzu-tech-marketing]
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: developer-application-platforms
  description: The Developer Application Platforms domain brings together technologies including on TAS, TAP, and ASAe. 
spec:
  owner: user:keith.lee
  profile:
    displayName: Developer Application Platforms
    picture: https://pbs.twimg.com/profile_images/1233138813939146752/YPCsKoIa_400x400.png


---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]