###############################
# SYSTEMS
###############################
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: where-for-dinner
  description: A fully functional microservices reference application
  tags:
    - java
    - dotnet
  links:
    - url: https://www.youtube.com/watch?v=IY784cDq1E8
      title: SpringOne Essentials Conference Talk (YouTube)
      type: video
    - url: https://github.com/vmware-tanzu/application-accelerator-samples/blob/main/where-for-dinner/README.md
      title: Application Source Code
      icon: github
      type: source
  annotations:
    # backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner'
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs
spec: 
  displayName: Where For Dinner Reference Application
  owner: user:greg.meyer
  domain: developer-experience
  profile:
    displayName: Where For Dinner Reference Application

####################################
# COMPONENTS
####################################
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-for-dinner-ui
  description: 'Node.js application frontend built using the React framework'
  links:
    - url: https://github.com/vmware-tanzu/application-accelerator-samples/blob/main/where-for-dinner/where-for-dinner-ui
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - nodejs
    - react
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-ui'
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/where-for-dinner-ui
spec:
  type: service
  lifecycle: experimental
  owner: user:greg.meyer
  system: where-for-dinner
  profile:
    displayName: Node.js React UI Application
  dependsOn: 
    - component:where-for-dinner-search
    - component:where-for-dinner-availability
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-for-dinner-search
  description: 'Spring Boot search component which also uses Spring Cloud components'
  links:
    - url: https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/where-for-dinner/where-for-dinner-search
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - springboot
    - springcloud
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-search'
    # backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs
spec:
  type: service
  lifecycle: experimental
  owner: user:greg.meyer
  system: where-for-dinner
  profile:
    displayName: 'Dinner Search'
  providesApis:
    - where-for-dinner-search
  dependsOn: 
    - resource:where-for-dinner-db
    - resource:where-for-dinner-messaging
    - component:where-for-dinner-search-proc
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-for-dinner-availability
  description: 'Dinner Availability'
  links:
    - url: https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/where-for-dinner/where-for-dinner-availability
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - springboot
    - springcloud
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-availability'
    # backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs
spec:
  type: service
  lifecycle: experimental
  owner: user:greg.meyer
  system: where-for-dinner
  profile:
    displayName: Spring Boot Availability Application
  providesApis:
    - where-for-dinner-availability
  dependsOn: 
    - resource:where-for-dinner-db
    - resource:where-for-dinner-messaging
    - component:where-for-dinner-search-proc
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-for-dinner-notify
  description: 'Dinner Notifications'
  links:
    - url: https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/where-for-dinner/where-for-dinner-notify
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - springboot
    - springcloud
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-notify'
    # backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs
spec:
  type: service
  lifecycle: experimental
  owner: user:greg.meyer
  system: where-for-dinner
  profile:
    displayName: Spring Boot Search Notification Application
  dependsOn: 
    - resource:where-for-dinner-messaging
    - component:where-for-dinner-search-proc
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-for-dinner-search-proc
  description: 'Search Processing'
  links:
    - url: https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/where-for-dinner/where-for-dinner-search-proc
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - springboot
    - springcloud
    - streaming
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-search-proc'
    # backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs
spec:
  type: service
  lifecycle: experimental
  owner: user:greg.meyer
  system: where-for-dinner
  profile:
    displayName: Spring Boot Search Processing Application
  dependsOn: 
    - resource:where-for-dinner-messaging
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-for-dinner-crawler
  description: 'Search Crawler'
  links:
    - url: https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/where-for-dinner/where-for-dinner-crawler
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - springboot
    - springcloud
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-crawler'
    # backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs
spec:
  type: service
  lifecycle: experimental
  owner: user:greg.meyer
  system: where-for-dinner
  profile:
    displayName: Spring Boot Search Crawler Application
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-for-dinner-crawler-python
  description: 'Search Crawler written in the Python language'
  links:
    - url: https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/where-for-dinner/where-for-dinner-crawler-python
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - springboot
    - springcloud
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-crawler-python'
    # backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs
spec:
  type: service
  lifecycle: experimental
  owner: user:greg.meyer
  system: where-for-dinner
  profile:
    displayName: Python Search Crawler Application
    
##################################
# Resources
##################################
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: where-for-dinner-db
  description: Where for Dinner Database
spec:
  type: database
  owner: user:greg.meyer
  system: where-for-dinner
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: where-for-dinner-messaging
  description: Where for Dinner Async Messaging
spec:
  type: message-broker
  owner: user:greg.meyer
  system: where-for-dinner

######################################
# APIs
######################################

# Made a start here but couldn't load from the URL in the definition.

# ---
# apiVersion: backstage.io/v1alpha1
# kind: API
# metadata:
#   name: where-for-dinner-search
#   description: The Search API
#   tags:
#     - api
#     - tanzu
#   links:
#     - url: https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/where-for-dinner/where-for-dinner-search
#       title: Source Code on GitHub
#       icon: github
#       type: source
#   annotations:
#     backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=where-for-dinner-search"
#     # backstage.io/techdocs-ref: url:https://github.com/benwilcock/springboot-maven/blob/main/
# spec:
#   type: openapi
#   lifecycle: experimental
#   owner: user:greg.meyer
#   system: where-for-dinner
#   definition:
#     $text: https://where-for-dinner.perfect300rock.com/api/search/v3/api-docs/
# ---
# apiVersion: backstage.io/v1alpha1
# kind: API
# metadata:
#   name: where-for-dinner-availability
#   description: The Availability API
#   tags:
#     - api
#     - tanzu
# spec:
#   type: openapi
#   lifecycle: experimental
#   owner: user:greg.meyer
#   system: where-for-dinner
#   definition:
#     $text: https://where-for-dinner.perfect300rock.com/api/availability/v3/api-docs/