###############################
# SYSTEMS
###############################
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tanzu-application-platform
  description: 'A platform for building, running, and maintaining applications on Kubernetes'
  tags:
    - java
    - dotnet
    - python
    - node
    - go
    - ruby
    - php
  links:
    - url: https://youtu.be/SDobPYHk_sQ
      title: Introduction to Tanzu Application Platform (YouTube)
      type: video
      icon: YouTube
    - url: https://via.vmw.com/tap
      title: Tanzu Application Platform Homepage
      type: website
      icon: WebAsset
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/tanzu-application-platform-system
spec: 
  displayName: Tanzu Application Platform
  owner: group:tanzu-engineering
  domain: developer-experience
  profile:
    displayName: Tanzu Application Platform

####################################
# COMPONENTS
####################################
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Kubernetes
  description: 'Kubernetes is the underlying orchestrator for the Tanzu Application Platform'
  links:
    - url: https://kubernetes.io/
      title: Website
      type: website
      icon: WebAsset
    - url: https://kubernetes.io/docs/home/
      title: Documentation
      type: website
      icon: WebAsset
    - url: https://kube.academy/
      title: VMware KubeAcademy Learning Zone
      type: website
      icon: WebAsset
  tags:
    - kubernetes
spec:
  type: service
  lifecycle: production
  providesApis:
    - cluster-api
  owner: group:CNCF
  system: tanzu-application-platform
  profile:
    displayName: Kubernetes
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-cli
  description: 'Tanzu CLI offers command line tools to create, run, and manage workloads on Tanzu Application Platform'
  links:
    - url: https://network.tanzu.vmware.com/products/tanzu-application-platform/
      title: Download (Tanzu Network)
      type: binary
      icon: FileDownload
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/cli-plugins-tanzu-cli.html
      title: Documentation (v1.5)
      type: website
      icon: WebAsset
    - url: https://via.vmw.com/tap
      title: Tanzu Application Platform (Product Homepage)
      type: website
      icon: WebAsset
  tags:
    - tanzu-cli
    - tanzu-application-platform
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/tanzu-application-platform-system
spec:
  type: library
  lifecycle: production
  owner: group:tanzu-engineering
  system: tanzu-application-platform
  profile:
    displayName: Tanzu CLI Command Line
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: supply-chain-choreographer
  description: 'Supply Chain Choreographer is based on open source Cartographer. It allows you to create pre-approved paths to production by integrating Kubernetes resources with the elements of your existing toolchains.'
  links:
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
      title: Documentation
      type: website
      icon: WebAsset
    - url: https://tanzu.vmware.com/content/blog/what-is-supply-chain-choreography-and-why-should-you-care
      title: 'What Is Supply Chain Choreography? (Blog)'
      type: website
      icon: WebAsset
    - url: https://via.vmw.com/tap
      title: Tanzu Application Platform (Homepage)
      type: website
      icon: WebAsset
  tags:
    - supply-chain-choreographer
    - tanzu-application-platform
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/tanzu-application-platform-system
spec:
  type: library
  lifecycle: production
  owner: group:tanzu-engineering
  system: tanzu-application-platform
  profile:
    displayName: Supply Chain Choreographer
  dependsOn: 
    - component:kubernetes
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: application-accelerator
  description: 'Application Accelerator for VMware Tanzu helps you bootstrap developing your applications and deploying them in a discoverable and repeatable way.'
  links:
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
      title: Documentation
      type: website
      icon: WebAsset
  tags:
    - tanzu-application-platform
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/tanzu-application-platform-system
spec:
  type: service
  lifecycle: production
  owner: group:tanzu-engineering
  system: tanzu-application-platform
  profile:
    displayName: application-accelerator
  dependsOn: 
    - component:kubernetes
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: application-single-sign-on
  description: 'Application Single Sign-On for VMware Tanzu (AppSSO) provides APIs for curating and consuming a “Single Sign-On as a service” offering on Tanzu Application Platform.'
  links:
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
      title: Documentation
      type: website
      icon: WebAsset
  tags:
    - tanzu-application-platform
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/tanzu-application-platform-system
spec:
  type: service
  lifecycle: production
  owner: group:tanzu-engineering
  system: tanzu-application-platform
  profile:
    displayName: application-single-sign-on
  dependsOn: 
    - component:kubernetes
---

#####################################
# Templates
#####################################

# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: comp-name
#   description: ''
#   links:
#     - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
#       title: Documentation
#       type: website
#       icon: WebAsset
#   tags:
#     - tanzu-application-platform
#   annotations:
#     backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/tanzu-application-platform-system
# spec:
#   type: service
#   lifecycle: production
#   owner: group:tanzu-engineering
#   system: tanzu-application-platform
#   profile:
#     displayName: comp-name
#   dependsOn: 
#     - component:kubernetes
# ---

######################################
# APIs
######################################

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cluster-api
  description: 'Cluster API is a Kubernetes subproject focused on providing declarative APIs and tooling to simplify provisioning, upgrading, and operating multiple Kubernetes clusters.'
  tags:
    - api
    - kubernetes
  links:
    - url: https://cluster-api.sigs.k8s.io/
      title: Cluster API Book
      type: website
      icon: WebAsset
    - url: https://github.com/kubernetes-sigs/cluster-api
      title: Cluster API Source Code
      type: source
      icon: github
spec:
  type: openapi
  lifecycle: production
  owner: group:CNCF
  #  system: where-for-dinner
  definition:
    $text: https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json
---