###############################
# SYSTEMS
###############################
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tanzu-application-platform
  description: 'A platform for building, running, and maintaining applications on Kubernetes'
  tags:
    - java
    - dotnet
    - python
    - node
    - go
    - ruby
    - php
  links:
    - url: https://youtu.be/SDobPYHk_sQ
      title: Introduction to Tanzu Application Platform (YouTube)
      type: video
      icon: YouTube
    - url: https://via.vmw.com/tap
      title: Tanzu Application Platform Homepage
      type: website
      icon: WebAsset
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/tanzu-application-platform-system
spec: 
  displayName: Tanzu Application Platform
  owner: group:tanzu-engineering
  domain: developer-experience
  profile:
    displayName: Tanzu Application Platform

####################################
# COMPONENTS
####################################
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-cli
  description: 'Tanzu CLI offers command line tools to create, run, and manage workloads on Tanzu Application Platform'
  links:
    - url: https://network.tanzu.vmware.com/products/tanzu-application-platform/
      title: Download (Tanzu Network)
      type: binary
      icon: FileDownload
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/cli-plugins-tanzu-cli.html
      title: Documentation (v1.5)
      type: website
      icon: WebAsset
    - url: https://via.vmw.com/tap
      title: Tanzu Application Platform (Product Homepage)
      type: website
      icon: WebAsset
  tags:
    - tanzu-cli
    - tanzu-application-platform
  # annotations:
  #   backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-ui'
  #   backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/where-for-dinner-ui
spec:
  type: library
  lifecycle: production
  owner: group:tanzu-engineering
  system: tanzu-application-platform
  profile:
    displayName: Tanzu CLI Command Line
  # dependsOn: 
  #   - component:where-for-dinner-search
  #   - component:where-for-dinner-availability
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: supply-chain-choreographer
  description: 'Supply Chain Choreographer is based on open source Cartographer. It allows you to create pre-approved paths to production by integrating Kubernetes resources with the elements of your existing toolchains.'
  links:
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/scc-about.html
      title: Documentation (v1.5)
      type: website
      icon: WebAsset
    - url: https://tanzu.vmware.com/content/blog/what-is-supply-chain-choreography-and-why-should-you-care
      title: 'What Is Supply Chain Choreography? (Blog)'
      type: website
      icon: WebAsset
    - url: https://youtu.be/d8YMWmkKdes
      title: 'What Is New for Platform Operators in VMware Tanzu Application Platform? (YouTube)'
      icon: YouTube
      type: video
    - url: https://via.vmw.com/tap
      title: Tanzu Application Platform (Product Homepage)
      type: website
      icon: WebAsset
  tags:
    - supply-chain-choreographer
    - tanzu-application-platform
  # annotations:
  #   backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=where-for-dinner-ui'
  #   backstage.io/techdocs-ref: url:https://github.com/benwilcock/where-for-dinner-techdocs/where-for-dinner-ui
spec:
  type: library
  lifecycle: production
  owner: group:tanzu-engineering
  system: tanzu-application-platform
  profile:
    displayName: Supply Chain Choreographer
  # dependsOn: 
  #   - component:where-for-dinner-search
  #   - component:where-for-dinner-availability
---
