###############################
# SYSTEMS
###############################
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage-genai
  description: "Backstage Generative AI."
  tags:
    - backstage
    - genai
    - llm
  links:
    - url: https://youtu.be/GAzKCQO8Vt0
      title: Generative AI In Backstage (YouTube)
      type: video
      icon: YouTube
    - url: https://backstage.io/docs/overview/what-is-backstage/ 
      title: What is Backstage? 
      type: website 
      icon: WebAsset
  # annotations:
  #   backstage.io/techdocs-ref: url:https://github.com/benwilcock/backstage-genai-talk
spec: 
  owner: user:ben.wilcock
  domain: generative-ai
  profile:
    displayName: Backstage Generative AI
---
####################################
# COMPONENTS
####################################
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backchat
  description: 'Backchat is a proof-of-concept plugin that integrates Generative AI into Backstage.'
  links:
    - url: https://bckstage.io/
      title: Backstage Website
      type: website
      icon: WebAsset
    - url: https://backstage.io/docs/plugins/
      title: Backstage Plugin Documentation
      type: website
      icon: WebAsset
  tags:
    - backstage
    - genai
    - backchat
spec:
  type: service
  lifecycle: production
  owner: user:ben.wilcock
  system: backstage-genai
  dependsOn: resource:localai
  profile:
    displayName: "Backchat: Backstage GenAI Plugin"
---
####################################
# RESOURCES
####################################
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: localai
  description: 'LocalAI provides a OpenAI API compatible service for private AI (self-hosted) use.'
  links:
    - url: https://localai.io/
      title: LocalAI Website
      type: website
      icon: WebAsset
  tags:
    - LocalAI
    - PrivateAI
    - genai
spec:
  type: service
  lifecycle: production
  providesApis:
    - openai-api
  owner: user:ben.wilcock
  system: backstage-genai
  dependencyOf: component:backchat
  profile:
    displayName: "LocalAI: OpenAI API Server"
---

