# SYSTEMS
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: polyglot-demo-apps
  description: A series of simple apps written in different programming languages and designed to demonstrate the power of supply chains and buildpacks in the Tanzu Application Platform
  tags:
    - java
    - dotnet
    - nodejs
    - python
    - supply-chain
    - demo
  links:
    - url: https://via.vmw.com/tap-java-sc
      title: Java (Spring) Video
      type: video
    - url: https://github.com/benwilcock/springboot-maven
      title: Java (Spring) Source Code
      icon: github
      type: source
    - url: https://via.vmw.com/tap-dotnet-sc
      title: .Net Core Video
      type: video
    - url: https://github.com/benwilcock/dotnet-aspcore
      title: .Net Core Source Code 
      icon: github
      type: source
    - url: https://via.vmw.com/tap-python-sc
      title: Python Video
      type: video
    - url: https://github.com/benwilcock/python-pipenv
      title: Python Source Code
      icon: github
      type: source
    - url: https://via.vmw.com/tap-node-sc
      title: Node.js Video
      type: video
    - url: https://github.com/benwilcock/node-express
      title: Node.js Source Code
      icon: github
      type: source
spec: 
  displayName: Polyglot Supply Chain Demo Applications
  owner: user:ben.wilcock
  domain: developer-application-platforms
  profile:
    displayName: Simple [Polyglot] Demo Applications


# COMPONENTS
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-maven-polyglot-demo
  # This is an extra long description with Markdown
  description: Java microservice (Spring Boot) built using Maven.
  links:
    - url: https://github.com/benwilcock/springboot-maven
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - java
    - supply-chain
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=springboot-maven"
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/springboot-maven/blob/main/
spec:
  type: service
  lifecycle: production
  owner: user:ben.wilcock
  system: polyglot-demo-apps
  providesApis:
    - springboot-maven-messages-api
  profile:
    displayName: Java (Spring) Demo Application
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-aspcore-polyglot-demo
  # This is an extra long description with Markdown
  description: '.Net ASP Core with Razer Pages'
  links:
    - url: https://github.com/benwilcock/dotnet-aspcore
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - dotnet
    - supply-chain
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=dotnet-aspcore'
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/dotnet-aspcore/blob/main/
spec:
  type: service
  lifecycle: production
  owner: user:ben.wilcock
  system: polyglot-demo-apps
  profile:
    displayName: .Net ASP Core Demo Application
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-express-polyglot-demo
  # This is an extra long description with Markdown
  description: 'Node.js with Express'
  links:
    - url: https://github.com/benwilcock/node-express
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - nodejs
    - supply-chain
    - demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=node-express'
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/node-express/blob/main/
spec:
  type: service
  lifecycle: production
  owner: user:ben.wilcock
  system: polyglot-demo-apps
  profile:
    displayName: Node.js Express Demo Application
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-pipenv-polyglot-demo
  # This is an extra long description with Markdown
  description: 'Python (Pipenv) with Flask'
  links:
    - url: https://github.com/benwilcock/python-pipenv
      title: Source Code on GitHub
      icon: github
      type: source
  tags:
    - nodejs
    - supply-chain
    - demo
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=python-pipenv'
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/python-pipenv/blob/main/
spec:
  type: service
  lifecycle: production
  owner: user:ben.wilcock
  system: polyglot-demo-apps
  profile:
    displayName: Python Pipenv Demo Application

# APIs
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: springboot-maven-messages-api
  description: Used to get a list of messages using a REST style API.
  links:
    - url: https://github.com/benwilcock/springboot-maven
      title: Source Code on GitHub
      icon: github
      type: source
  annotations:
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=springboot-maven"
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/springboot-maven/blob/main/
spec:
  type: openapi
  lifecycle: production
  owner: user:ben.wilcock
  system: polyglot-demo-apps
  definition:
    $text: https://github.com/benwilcock/springboot-maven/blob/main/openapi/openapi.json
---
