site_name: ibm-granite-8b-code-instruct
site_description: IBM Granite 8B Code Instruct
# site_author: user:ben.wilcock
nav:
  - "IBM Granite 8B Code Instruct™": ibm-granite-8b-code-instruct.md
  
plugins:
  - techdocs-core
metadata:
  namespace: default
kind: resource